@startuml Si

class IceClimbers
class Actualizable 
class Ventana 
class Dibujo
class Personaje
class Enemigos
class Escalador
class Yeti
class Foca 
class Pajaro
class Terodactilo
class Nube
class Oso
class Berenjena
class Zanahoria
class Verduras
class Plataformas
class Ladrillo
class Estalactita
class Martillo
class Hielo 
class Escenario
class Objetos

IceClimbers --* Personaje
IceClimbers --* Escenario
IceClimbers --* Enemigos
IceClimbers --* Objetos
IceClimbers o-- Actualizable
IceClimbers o-- Ventana
IceClimbers o-- Dibujo

Personaje --|> Escalador

Escalador --o Martillo
Escalador --o Berenjena
Escalador --o Zanahoria

Escenario --|> Plataformas

Objetos --|> Martillo
Objetos --|> Verduras
Objetos --|> Hielo

Plataformas --|> Nube
Plataformas --|> Estalactita
Plataformas --|> Ladrillo

Verduras --|> Berenjena 
Verduras --|> Zanahoria

Enemigos --|> Yeti
Enemigos --|> Oso
Enemigos --|> Foca
Enemigos --|> Pajaro
Enemigos --|> Terodactilo

Yeti --o Hielo
Foca --o Hielo

@enduml

